services:
# Api Server ##################################
  pymongo_api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos_router
    ports:
      - 8080:8080
    networks:
     app-network:
        ipv4_address: 173.17.20.1        
  
    environment:
      MONGODB_URL: "mongodb://mongos_router"
      MONGODB_DATABASE_NAME: "somedb"


   #сервер конфигурации configSrv
  configSrv:
    image: mongo:latest # docker образ
    container_name: configSrv 
    restart: always
    ports:
      - "27001:27001"
    networks:
      app-network:
        ipv4_address: 173.17.10.1
    volumes:
      - mongo_cluster_config_srv:/data/db
    command:
      [
        "--configsvr",  #запуск в режиме конфигурации
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27001"
      ] 
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

 # Router
  mongos_router:
    image: mongo:latest
    container_name: mongos_router
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.0.2
    command:
      [
        "mongos", #обычная mongo в режиме роутера
        "--configdb", 
        "config_server/configSrv:27001", #передача данных сервера конфигурации
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s



  # Shard 1 1
  shard1-1:
    container_name: shard1-1
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard11_data:/data/db
    ports:
      - "27011:27011"
    networks:
      app-network:
        ipv4_address: 173.17.1.1  
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27011"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Shard 1 2
  shard1-2:
    container_name: shard1-2
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard12_data:/data/db
    ports:
      - "27012:27012"
    networks:
      app-network:
        ipv4_address: 173.17.1.2  
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27012"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  # Shard 1 3
  shard1-3:
    container_name: shard1-3
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard13_data:/data/db
    ports:
      - "27013:27013"
    networks:
      app-network:
        ipv4_address: 173.17.1.3  
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard1", 
        "--bind_ip_all",
        "--port",
        "27013"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s



  # Shard 2 1 
  shard2-1:
    container_name: shard2-1
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard21_data:/data/db
    ports:
      - "27021:27021"
    networks:
      app-network:
        ipv4_address: 173.17.2.1        
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27021"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s


  # Shard 2 2 
  shard2-2:
    container_name: shard2-2
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard22_data:/data/db
    ports:
      - "27022:27022"
    networks:
      app-network:
        ipv4_address: 173.17.2.2        
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27022"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s      

  # Shard 2 3 
  shard2-3:
    container_name: shard2-3
    image: dh-mirror.gitverse.ru/mongo:latest
    volumes:
      - mongo_cluster_shard23_data:/data/db
    ports:
      - "27023:27023"
    networks:
      app-network:
        ipv4_address: 173.17.2.3        
    command:
      [
        "--shardsvr", #запуск в режиме шардинга
        "--replSet",
        "shard2", 
        "--bind_ip_all",
        "--port",
        "27023"
      ]
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s   

###############################################


networks:
  app-network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.0.0/16

volumes:
 mongo_cluster_config_srv:
 mongo_cluster_shard11_data:
 mongo_cluster_shard12_data:
 mongo_cluster_shard13_data:
 mongo_cluster_shard21_data:
 mongo_cluster_shard22_data:
 mongo_cluster_shard23_data: